FROM node:25 AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY website ./website
COPY database ./database

RUN npm run build:website

FROM nginx

COPY --from=build /usr/src/app/website/dist/ /usr/share/nginx/html
COPY website/nginx/default.conf /etc/nginx/conf.d/default.conf
