# Docker file for setting up the client side of web server 

#Using the official image of Nginx
FROM nginx

#Copy the index.html file to the current folder of nginx
COPY index.html /usr/share/nginx/html