sources:
  - key: hmd
    name: Human Mortality Database
    url: https://www.mortality.org
    citation: Human Mortality Database. University of California, Berkeley (USA), and Max Planck Institute for Demographic Research (Germany).
    license: Use subject to HMD licensing terms.
  - key: hfd
    name: Human Fertility Database
    url: https://www.humanfertility.org
    citation: Human Fertility Database. Max Planck Institute for Demographic Research (Germany) and Vienna Institute of Demography (Austria).
    license: Use subject to HFD licensing terms.
  - key: gutierrezetal2023
    name: Replication Data for Projections of human kinship for all countries
    url: https://doi.org/10.7910/DVN/FKCRHW 
    citation: D. Alburez-Gutierrez, I. Williams, & H. Caswell, Projections of human kinship for all countries, PNAS (2023).
    license: CC0.1.0
  - key: kashnitskyetal2019
    name: Replication Data for Geofaceting – Aligning small-multiples for regions in a spatially meaningful way
    url: https://doi.org/10.4054/DemRes.2019.41.17
    citation: I. Kashnitsky, & J. M. Aburto, Geofaceting – Alligning small-multiples for regions in a spatially meaningful way. Demographic Research (2019).
    license: MIT license
  - key: carollo2025
    name: Replication Data for Analysis of Time-to-Event Data With Two Time Scales. An Application to Transitions out of Cohabitation.
    url: https://doi.org/10.1177/00491241251374193
    citation: A. Carollo, H. Putter, P. H. C. Eilers, & J. Gampe. Analysis of Time-to-Event Data With Two Time Scales. An Application to Transitions out of Cohabitation. Sociological Methods & Research (2025).
    license: CC BY 4.0
  - key: abramsetal2026
    name: Replication Data for Insights into US life expectancy stagnation from birth cohort mortality dynamics.
    url: https://osf.io/xf57e
    citation: L. Abrams, O. Bramajo, A. van Raalte, M. Myrskylä, & N.K. Mehta. Insights into US life expectancy stagnation from birth cohort mortality dynamics. Proc. Natl. Acad. Sci. (2026).
    license: CC BY-NC 4.0
